# Generated by Django 4.2.30 on 2026-07-09 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_to', models.DateTimeField(blank=True, null=True)),
                ('repeat_type',
                 models.CharField(blank=True,
                                  choices=[('hourly', 'Каждый час'),
                                           ('daily', 'Ежедневно'),
                                           ('weekly', 'Еженедельно')],
                                  default=None,
                                  max_length=20,
                                  null=True)),
                ('repeat_interval',
                 models.PositiveIntegerField(blank=True, null=True)),
                ('status',
                 models.CharField(choices=[('active', 'Активна'),
                                           ('done', 'Выполнена'),
                                           ('cancelled', 'Отменена'),
                                           ('deleted', 'Удалена')],
                                  default='active',
                                  max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='tasks',
                                   to='reminder.user')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['user', 'status'],
                                 name='reminder_ta_user_id_48e620_idx'),
                    models.Index(fields=['user', 'due_to'],
                                 name='reminder_ta_user_id_397b15_idx')
                ],
            },
        ),
    ]
