# Generated by Django 4.2.30 on 2026-07-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='repeat_type',
            field=models.CharField(blank=True,
                                   choices=[('hourly', 'Каждый час'),
                                            ('daily', 'Ежедневно'),
                                            ('weekly', 'Еженедельно')],
                                   default='daily',
                                   max_length=20,
                                   null=True),
        ),
    ]
