# Generated by Django 4.2.30 on 2026-07-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_alter_task_repeat_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('reminder_time', models.DateTimeField()),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('reaction',
                 models.CharField(blank=True, max_length=10, null=True)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('task',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='reminders',
                                   to='reminder.task')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['reminder_time'],
                                 name='reminder_re_reminde_5e140e_idx'),
                    models.Index(fields=['sent_time'],
                                 name='reminder_re_sent_ti_c72af3_idx'),
                    models.Index(fields=['message_id'],
                                 name='reminder_re_message_e1bb84_idx'),
                    models.Index(fields=['task'],
                                 name='reminder_re_task_id_b09908_idx')
                ],
            },
        ),
    ]
