# Generated by Django 4.2.30 on 2026-07-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_reminder'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reminder',
            name='reminder_re_message_e1bb84_idx',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
