# Generated by Django 4.2.30 on 2026-07-11 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder',
         '0005_remove_reminder_reminder_re_message_e1bb84_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('event_type',
                 models.CharField(choices=[
                     ('created', 'Создана'),
                     ('reminder_sent', 'Напоминание отправлено'),
                     ('undated_card_sent', 'Карточка без даты'),
                     ('evening_question_sent', 'Вечерний вопрос'),
                     ('completed', 'Выполнена'), ('cancelled', 'Отменена'),
                     ('rescheduled', 'Перенесена'),
                     ('date_set', 'Дата установлена'), ('deleted', 'Удалена'),
                     ('digest_sent', 'Дайджест отправлен')
                 ],
                                  max_length=30)),
                ('message_id',
                 models.BigIntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='events',
                                   to='reminder.task')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['task', 'created_at'],
                                 name='reminder_ta_task_id_657069_idx')
                ],
            },
        ),
    ]
