# Generated by Django 4.2.30 on 2026-07-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0009_alter_task_repeat_type_minutely'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='repeat_type',
            field=models.CharField(blank=True,
                                   choices=[('minutely', 'Каждую минуту'),
                                            ('hourly', 'Каждый час'),
                                            ('daily', 'Ежедневно'),
                                            ('weekly', 'Еженедельно'),
                                            ('monthly', 'Ежемесячно')],
                                   default='daily',
                                   max_length=20,
                                   null=True),
        ),
    ]
